### ISSUE TITLE
L.TileLayer is not a function - conflict when using 3rd party map tiles

### ISSUE THREAD

**Issue by gagwithgaffer** [Azure-Samples/azure-maps-leaflet#1]
I'm using the latest azure-maps-leaflet.min.js  with Leaflet 1.71

This plugin works fine if we **only** want to use map tiles from Azure, but I dont! 

I should be able to use other 3rd party map tiles as well but the way you've written your js script means we get a conflict on "L.TileLayer" 

JS Error in console:

mapCommon.js:90 Uncaught (in promise) TypeError: L.tileLayer.azureMaps is not a function
    at mapCommon.js:90
    at new Promise (<anonymous>)
    at initiliazeMap (mapCommon.js:27)
    at updateDefaultMapStyle (Design:648)
    at HTMLSelectElement.onchange (Design:311)

The above error is thrown when trying to use 3rd party map tiles like OpenStreetMap

I'm trying to use OpenStreetMaps in addition to giving the user access to the Azure map tiles:

```
// THIS NO LONGER WORKS AS SOON AS WE REFERENCE "azure-maps-leaflet.min.js"
// Set the map instance, view and location, then set zoom.
map = L.map('mapDiv').setView([latitude, longitude], 10);
map.setZoom(setInitialZoom);

L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
	attribution: '&copy; <a href="http://openstreetmap.org/copyright">OpenStreetMap</a> contributors',
	maxZoom: maxixmumZoom,
}).addTo(map);

////////////////////////////////////

// This code does work, but no other 3rd party map tiles service will...
L.tileLayer.azureMaps({ authOptions: authOptions }).addTo(map)

var layer = new L.TileLayer.AzureMaps({
	authOptions: authOptions,
	tilesetId: 'microsoft.imagery',
	language: 'fr-FR'
});
map.addLayer(layer);

```
This issues is something to do with the use of "L.tileLayer.azureMaps"

Please fix this, its pointless trying to use Azure map tiles if its going to stop us using anything else, people expect choices, not exclusivity...

**Comment by rbrundritt** [comment]
Took a look at this and made the required fix. This should now work as expected.
